---
--- Generated by Luanalysis
--- Created by slq
--- DateTime: 2021/9/29 13:33
--- use for test lib
---
---
local cache = require("cache")
local system = require("system")
local filem = require("filemonitor")
local function check()
    local cache_key = "hostname"
    local old = cache.get_cache(cache_key)
    if old == nil then
        local current = system.hostname()
        cache.set_cache(cache_key, current)
        print(cache_key)
        print(current)
        return
    end
    local current = system.hostname()
    if old ~= current then
        trigger({Content=current})
        set_cache(cache_key, current)
    end
    filem.exist("./lua.go")
end
check()

