---
--- Generated by Luanalysis
--- Created by 18332.
--- DateTime: 2021/10/27 14:53
---
local sc_file = require("file")
local cache = require("cache")
local system = require("system")
local filemonitor = require("filemonitor")

local function check()
    local kube_node = cache.get_global_cache('kube_node')
    if kube_node == nil or not kube_node then
        return
    end
    local file = get_configfile()
    if not sc_file.file_exist(file) then
        return
    end
    -- 000 110 100 100   420
    -- --- rw- r-- r--
    filemonitor.priv_limit(file, 420)
end

function get_configfile()
   return system.process_command("kube-proxy","config")
end

check()