---
--- Generated by Luanalysis
--- Created by 18332.
--- DateTime: 2021/10/28 10:00
---


local cache = require("cache")
local system = require("system")

function check()
    local kube_node = cache.get_global_cache('kube_node')
    if kube_node == nil or not kube_node then
        return
    end
    local conf = get_configfile()
    cache_mode = cache.get_cache("authorization-mode")
    if conf == "AlwaysAllow" and cache_mode ~= "AlwaysAllow" then
        trigger({Content=conf})
        cache.set_cache("authorization-mode",conf)
    end
end

function get_configfile()
    return system.process_command("kubelet","authorization-mode")
end

check()