---
--- Generated by Luanalysis
--- Created by 18332.
--- DateTime: 2021/10/28 10:50
---

local cache = require("cache")
local system = require("system")

function check()
    local kube_node = cache.get_global_cache('kube_node')
    if kube_node == nil or not kube_node then
        return
    end
    local conf = get_configfile()
    cache_mode = cache.get_cache("client-ca-file")

    if conf == "" then
        if not cache_mode then
            trigger({Content=conf})
            cache.set_cache("client-ca-file",conf)
        end
    end
end

function get_configfile()
    return system.process_command("kubelet","client-ca-file")
end

check()
