---
--- Generated by Luanalysis
--- Created by 18332.
--- DateTime: 2021/10/27 11:35
---

local sc_file = require("file")
local cache = require("cache")
local filemonitor = require("filemonitor")

local function check(files)
    local kube_node = cache.get_global_cache('etcd')
    if kube_node == nil or not kube_node then
        return
    end
    for i, file in ipairs(files) do
        if not sc_file.file_exist(file) then
            return
        end
        -- 000 110 100 100   420
        -- --- rw- r-- r--
        filemonitor.priv_limit(file, 700)
    end

end
-- 配置文件
files = {"/var/lib/etcd"}

check(files)